### ISSUE TITLE
Inform users of project status

### ISSUE THREAD

**Issue by fulldecent** [jalcine/bugzilla-openid#5]
This project enjoys a high profile link from https://wiki.mozilla.org/Bugzilla:OpenID_Auth_Plugin

Please update that link to note this project is not active.

Please update README.md to note this project is not active.

If possible, please recommend another project which solves the problem.

**Comment by jalcine** [comment]
Thanks for informing me @fulldecent.

AFAIK, there isn't another project like this (from what I know).

**Comment by jalcine** [comment]
@fulldecent is it possible to get the Wiki updated?
